# Generated by Django 3.2.9 on 2021-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='foods/%Y/%m/%d/')),
                ('price', models.FloatField(max_length=10)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField(max_length=20)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
    ]
